main: github.BTEPlotSystem.BTEPlotSystem
version: 1.2
api-version: 1.12.2
name: AlpsBTE-PlotSystem
author: R3tuxn & Cinnazeyy
depend: [HeadDatabase, HolographicDisplays]

commands:
  spawn:
    description: Teleport to the spawn
    usage: /spawn
  hub:
    description: Alternative to the spawn command
    usage: /hub
  tpp:
    description: Teleport to a player
    usage: /tpp <Player>
  companion:
    description: Open the Companion menu
    permission: alpsbte.plot
    usage: /companion
  link:
    description: Sends you the links of the plot you are currently on
    permission: alpsbte.plot
    usage: /link
  submit:
    description: Submit a unfinished plot
    permission: alpsbte.plot
    usage: /submit, /submit <ID>
  abandon:
    description: Abandon a unfinished plot
    permission: alpsbte.plot
    usage: /abandon, /abandon <ID>
  undosubmit:
    description: Undo a submission of a unreviewed plot
    permission: alpsbte.plot
    usage: /undosubmit, /undosubmit <ID>
  feedback:
    description: Shows all feedback information of a plot
    permission: alpsbte.plot
    usage: /feedback <ID>
  plots:
    description: Shows all plots of the given player
    permission: alpsbte.plot
    usage: /plots, /plots <Player>
  plot:
    description: Teleport to a plot
    permission: alpsbte.review
    usage: /plot <ID>
  review:
    description: Open the review or review plot menu
    permission: alpsbte.review
    usage: /review
  undoreview:
    description: Undo a review of a plot
    permission: alpsbte.review
    usage: /undoreview <ID>
  sendfeedback:
    description: Sets the feedback of a plot
    permission: alpsbte.review
    usage: /sendfeedback <ID> <Text>
  editplot:
    description: Enable/disble build permissions for reviewers on a plot
    permission: alpsbte.review
    usage: /editplot
  deleteplot:
    description: Delete a plot
    permission: alpsbte.admin
    usage: /deleteplot <ID>
  generateplot:
    description: Generate a new plot
    permission: alpsbte.admin
    usage: /generateplot <ID>
  sethologram:
    description: Sets the position of a hologram
    permission: alpsbte.admin
    usage: /sethologram <name>
  preload:
    description: Reload config and holograms
    permission: alpsbte.admin
    usage: /preload
  tpll:
    description: teleport to a position in the plot, using irl coordinates
    usage: /tpll <long> <lat>
  invite:
    description: accept or deny an incoming invite
    usage: /invite accept/deny <PlotID>
  pss:
    description: Command for setting up the database
    permission: alpsbte.admin
    usage: /pss
permissions:
  alpsbte.admin:
    description: Manager permissions